plugin: aws_ec2

regions:
  - eu-west-2

hostnames:
  - private-ip-address
  
filters:
  tag:Name:
    - kdm-master-node
    - kdm-etcd-node
    - kdm-worker-node

compose:
  ansible_ssh_user: "'ec2-user'"
  ansible_python_interpreter: "'/usr/libexec/platform-python'"

groups:
  master: "'kdm-master-node' == (tags.Name)"
  etcd: "'kdm-etcd-node' == (tags.Name)"
  worker: "'kdm-worker-node' == (tags.Name)"